# POST client

POST http://localhost:3000/client
Content-Type: application/json

{
    "name": "string",
    "cnpj": "52345678901234",
    "corporate_name": "string",
    "phone": "string",
    "address_name": "string",
    "cep": "12345678",
    "city": "string",
    "district": "string",
    "number": "string",
    "state": "string",
    "option": "string"
}