version: "2.6"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - PGDATABASE=flights
      - PGUSER=root
      - PGHOST=db
      - PGPASSWORD=123
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: "node_db"
    restart: always
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=flights
    volumes:
      - pgdata:/app/data

volumes:
  pgdata:
